language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - pyinstaller --onefile main.py -n poe_gems
deploy:
  provider: releases
  api_key:
    secure: $RELEASES_API_KEY
  file: ./dist/poe_gems.exe
  skip_cleanup: true
  on:
    draft: true
    all_branches: true
