os: windows
language: shell
before_install:
  - choco install python --version 3.7.4
  - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
  - py -m pip install --upgrade pip
install:
  - pip install -r requirements.txt
before_script:
  - pytest
script:
  - pyinstaller --onefile poe/main.py -n poe.exe
deploy:
  provider: releases
  api_key:
    secure: $RELEASES_API_KEY
  file_glob: true
  file: "./dist/poe*"
  skip_cleanup: true
  on:
    tags: true
    branch: master
